export enum EntitlementKey {
  MAX_PATIENTS = 'MAX_PATIENTS',
  MAX_STAFF_SEATS = 'MAX_STAFF_SEATS',
  CAN_EXPORT_PDF = 'CAN_EXPORT_PDF',
  CAN_USE_FINANCIAL_MODULE = 'CAN_USE_FINANCIAL_MODULE',
  CAN_CUSTOM_BRAND = 'CAN_CUSTOM_BRAND',
  MAX_STORAGE_MB = 'MAX_STORAGE_MB',
  API_ACCESS_ENABLED = 'API_ACCESS_ENABLED',
}

export const REQUIRE_QUOTA_KEY = 'REQUIRE_QUOTA_KEY';
export const REQUIRE_FEATURE_KEY = 'REQUIRE_FEATURE_KEY';
